### ISSUE TITLE
Absolute file paths cannot be browsed in audit pane

### ISSUE THREAD

**Issue by tunnelshade** [pwntester/codeql.nvim#2]
### Issue

I created a codeql database using absolute source path. So, when my query returns results I see that the auditPane links to the source files and prepended by DatabasePath.

### Fix

In case of absolute paths use them directly & if paths are relative, prepend `databasePath/src`

*PS: I really want to fix this myself, please point me to right place. Lua is confusing so far for me*

**Comment by pwntester** [comment]
I saw you already found the right spot to fix it, thanks! I added some comments to your PR.

BTW, I wrote all the audit panel part in vimscript before starting playing with lua, but when time permits, I will move all that code to lua as well since rendering too many results would benefit from lua extra speed
