### ISSUE TITLE
Query buffer format on BufWrite

### ISSUE THREAD

**Issue by tunnelshade** [pwntester/codeql.nvim#9]
Hi @pwntester 

Adding following line in the plugin with an option of `g:codeql_fmt_onsave` defaulted to `0` should allow users to autoformat query buffers.

``` vim
if g:codeql_fmt_onsave
  autocmd FileType ql autocmd BufWrite <buffer> :%!codeql query format -
endif
```

I wanted to send a pull request but current directory layout confused me. This plugin at present sets filetype as `ql` but files in `ftdetect` and `ftplugin` are named as `codeql.vim`. As per my understanding it should be `ql.vim` (same as filetype being set) for vim to even load them. Is this intentional? or am I missing something?

If you can tell me which file to add the above snippet, I can send a PR, but adding `let g:codeql_fmt_onsave = 0` to `autoload`.

**Comment by pwntester** [comment]
Thanks for the suggestion @tunnelshade. I had quite a mess with the directory structure since I initially was using the codeql filetype.
I - hopefully- sorted it out and added the option you suggested for autoformatting on BufWrite.
Also, in case you didnt know about it, the LSP server can format the buffer as well on demand. For example, in my config I can do that with <leader>=:

```
	map('n','<leader>=', '<cmd>lua vim.lsp.buf.formatting()<CR>')
```

Thanks!
